language: java
jdk:
  - oraclejdk8
before_install: chmod a+x gradlew
deploy:
  skip_cleanup: true
  provider: script
  script: "./gradlew uploadArchives"
  on:
    branch: master
env:
  matrix:
    secure: "sckIUbfFQU+pKYbpLlruobsEeOI8ICniofb5TBASN+kuiMJRk6HUwgjLtUR5qG7DYywc2SvT+GmCvstMyYR+S4NnrD7ZzN09dTtMFkMRon7WdhSchVILeNV+wo1o+gwGUtBjQ0GBeszC2jXTEYR8QZbLtkcxP4aEnKjSf+kH4DWS4lXFJY4omEa9DZaJmvNn51v9seldRl76Lk8x6diwMHEYn1SfI2qmsPidmjCpU7Ilj/x8N+w4B6lFJsngPxWJgeGrqJ23fb8yJay5h1qCqEGOMXFSqaYYFhFFexkWS5Xu8mppR9oPbmSpPaaN5fwSiFblTwQfld7zz1v7bir7DC5F4Yu9D9JM4rjqOoh0awaEfW9PkXeMsPY/qn1SiMRi3FofmUv4S9gnLHewEIuE9+R0WsPjmAiXE5JHTJ9JPMhpaTPC13zuwsKTVZYZVorApSajXwqEY0ivzVk65JGenNrDpYi3x1Pzfn1lX7IbLA5cAFD+csXa+jCrpr4vO/s/44j2NVfTL3ojoy3yawRATZZ3UmQ9PkFDU4ydKznWXn5qBVgPWUaTrlUj68CQBRpVYl9Oa3Lj4Mt06L9AwL3O+i+cSNZwzYXl9slzV2/FFQfWhQZDfDg03h1dTQH3WrIOxj26s0oa8AWU7rAI+fouwlqX1V0JqmBdphBD9APj2Rw="
